### ISSUE TITLE
Move the Epinio dashboard to its own repo

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#178]
We should move the Epinio dashboard from the rancher/dashboard@epinio-dev repository to its own repository ([epinio/ui](https://github.com/epinio/ui))
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/ui/pull/249
- [x] [ui] switch defaul epinio/ui branch to main
- [x] [ui] build new dashboard shell, use in epinio/ui
- [x] [ui] add ci gates to epinio/ui
- [x] Remove pkg/epinio, build steps and other references from  `rancher/dashbaord`
- [x] [ui] add issue / pr template
- [ ] https://github.com/epinio/ui/issues/248
- [x] [ui] add branch protection
```

**Comment by richard-cox** [comment]
@scures you may need to be in https://github.com/orgs/epinio/teams/epinio/members to transfer issues from epinio/epinio

@enrichman I've added you to https://github.com/orgs/epinio/teams/ui/members, that should help  you transfer issues to epinio/ui

**Comment by richard-cox** [comment]
Blocked on
- merging of dashboard changes in rancher/dashbaord `epinio-dev` back to rancher/dashboard `master`
- a new shell npm release that contains them

**Comment by richard-cox** [comment]
Tracking some prs
- use new rancher shell https://github.com/epinio/ui/pull/257
- Remove epinio from rancher/dashboard - https://github.com/rancher/dashboard/pull/9208
- gh issue/pr templates - https://github.com/epinio/ui/pull/256

**Comment by richard-cox** [comment]
Closing, all dependent parts done
