### ISSUE TITLE
[ui] Add/Edit service chart values 

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#252]
- To flesh out, but the UI side of https://github.com/epinio/epinio/issues/1633
- It's expected these work in the same way as application chart values
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/ui/issues/338
- [ ] https://github.com/epinio/ui/issues/339
- [ ] https://github.com/epinio/ui/issues/302
```

**Comment by richard-cox** [comment]
See https://github.com/epinio/epinio/issues/1633#issuecomment-1609171608

**Comment by richard-cox** [comment]
@torchiaf this will be complete when https://github.com/epinio/epinio/pull/2522 is integrated right?

**Comment by thehejik** [comment]
**Test Report**
* seems it works as expected
* So far only simple data types as strings (+ enum), integer (+ minimum, maximum, +enum) and bool are supported, lists and maps should be addressed by https://github.com/epinio/ui/issues/302
* Unable to Edit deployed service by clicking `Edit Config` which should be (I guess here) addressed by https://github.com/epinio/epinio/pull/2522

**Test** 
* run ` kubectl edit services.application.epinio.io -n epinio mysql-dev` and enter following (settings at `values` level):
```yaml
  settings:
    auth.rootPassword:
      type: string
    global.storageClass:
      enum:
      - default
      - local-path
      - none
      type: string
    primary.persistence.enabled:
      type: bool
    primary.service.ports.mysql:
      maximum: "3307"
      minimum: "3306"
      type: integer
```
* create a new service in UI by using modified `mysql-dev` service catalog and put reasonable values:
![pasted_image](https://github.com/epinio/ui/assets/12828077/e4e74810-8f97-4235-9ea8-ad89c90dc2cc)
* Verify by CLI that the values are propagated into the service:
```bash
$ epinio service show mysql-values-ui

🚢  Showing Service...

✔️  Details:
|       KEY       |                                     VALUE                                      |
|-----------------|--------------------------------------------------------------------------------|
| Name            | mysql-values-ui                                                                |
| Created         | 2023-08-31 16:30:09 +0200 CEST                                                 |
| Catalog Service | mysql-dev                                                                      |
| Version         | 8.0.31                                                                         |
| Status          | not-ready                                                                      |
| Used-By         |                                                                                |
| Internal Routes | xefb34329720317139eae966f094d-mysql-headless.workspace.svc.cluster.local:3306, |
|                 | xefb34329720317139eae966f094d-mysql.workspace.svc.cluster.local:3306           |

✔️  Settings
|             KEY             |   VALUE    |
|-----------------------------|------------|
| auth.rootPassword           | linux      |
| global.storageClass         | local-path |
| primary.persistence.enabled | true       |
| primary.service.ports.mysql |       3306 |

✔️  Credentials:
|         KEY         |   VALUE    |
|---------------------|------------|
| mysql-password      | wgPo5Mja1G |
| mysql-root-password | linux      |
```

**Comment by richard-cox** [comment]
Edit needs to big integrated / validated now https://github.com/epinio/epinio/pull/2522 has been completed

**Comment by richard-cox** [comment]
Thinking about it, lets make this issue an epic and create issues for Add (which we can say is complete for 1.10) and Edit (which will probably be for 1.11)

**Comment by torchiaf** [comment]
> @torchiaf this will be complete when [epinio/epinio#2522](https://github.com/epinio/epinio/pull/2522) is integrated right?

Now that 2522 is complete we can go forward with the UI.

**Comment by richard-cox** [comment]
I've split this out into two issues to denote the milestones each change will go in to
- https://github.com/epinio/ui/issues/338 (1.10)
- https://github.com/epinio/ui/issues/339 (1.11)

**Comment by richard-cox** [comment]
As part of this issue we should ensure custom chart values are validated as per https://github.com/epinio/ui/issues/299#issuecomment-1706593724

**Comment by richard-cox** [comment]
Given create and edit are in the code base and tested independently i'm going to close this issue as done.

We still have https://github.com/epinio/ui/issues/302, that is now targeted at 1.12
